name: Reddit Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs the bot every 5 minutes
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run_bot:
    runs-on: ubuntu-latest  # This runs the bot on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out the code from your GitHub repo

      - name: Set up Python
        uses: actions/setup-python@v2  # This sets up Python in the GitHub Actions environment
        with:
          python-version: '3.8'  # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to make sure it's the latest
          pip install praw  # Install the 'praw' library, which is used to interact with Reddit

      - name: Run the Reddit bot
        run: |
          python reddit_bot.py  # This runs your bot script
        env:
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}  # Pulls secret values from GitHub Secrets
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
